-- HAPI 2 - PATIOTIME (RESTORANT) - MariaDB / XAMPP
DROP DATABASE IF EXISTS patiotime_db;

CREATE DATABASE patiotime_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE patiotime_db;

CREATE TABLE KLIENT (
    KLI_ID CHAR(10) NOT NULL,
    KLI_EM VARCHAR(15) NOT NULL,
    KLI_MB VARCHAR(15) NOT NULL,
    KLI_GJIN CHAR(1) NOT NULL DEFAULT 'X',
    KLI_ZONA CHAR(3) NOT NULL DEFAULT 'XXX',
    KLI_TEL VARCHAR(13) NOT NULL,
    KLI_EMA VARCHAR(30) NOT NULL,
    PRIMARY KEY (KLI_ID),
    UNIQUE KEY UK_KLI_TEL (KLI_TEL),
    UNIQUE KEY UK_KLI_EMA (KLI_EMA),
    CONSTRAINT CHK_KLI_ID CHECK (KLI_ID REGEXP '^[A-Z][0-9]{8}[A-Z]$'),
    CONSTRAINT CHK_GJINIA CHECK (KLI_GJIN IN ('M','F','X')),
    CONSTRAINT CHK_ZONA CHECK (KLI_ZONA IN ('TIR','DUR','ELB','VLO','LON','XXX')),
    CONSTRAINT CHK_TEL_EMAIL CHECK (
        (KLI_TEL <> 'XXXXXXXXXXXXX') OR (KLI_EMA <> 'X')
    )
) ENGINE=InnoDB;

CREATE TABLE KONTAKT (
    KON_ID INT NOT NULL AUTO_INCREMENT,
    KLI_ID CHAR(10) NOT NULL,
    KON_SUB VARCHAR(50) NOT NULL,
    KON_MES TEXT,
    KON_DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (KON_ID),
    CONSTRAINT FK_KONTAKT_KLIENT FOREIGN KEY (KLI_ID)
        REFERENCES KLIENT(KLI_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE REZERVIM (
    REZ_ID INT NOT NULL AUTO_INCREMENT,
    KLI_ID CHAR(10) NOT NULL,
    REZ_PERSONA TINYINT NOT NULL,
    REZ_DATA DATE NOT NULL,
    REZ_ORA VARCHAR(10) NOT NULL,
    REZ_REGJ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REZ_ID),
    CONSTRAINT CHK_PERSONA CHECK (REZ_PERSONA BETWEEN 1 AND 20),
    CONSTRAINT FK_REZERVIM_KLIENT FOREIGN KEY (KLI_ID)
        REFERENCES KLIENT(KLI_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ADMIN (
    ADM_ID TINYINT NOT NULL AUTO_INCREMENT,
    ADM_USER VARCHAR(20) NOT NULL,
    ADM_PASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADM_ID),
    UNIQUE KEY UK_ADM_USER (ADM_USER)
) ENGINE=InnoDB;

INSERT INTO ADMIN (ADM_USER, ADM_PASS)
VALUES ('admin', 'ndryshoje_me_php');
